# Generated by Django 2.1.7 on 2019-02-25 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190225_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookedevents', to=settings.AUTH_USER_MODEL),
        ),
    ]
