# Generated by Django 2.1.7 on 2019-02-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190225_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
